image:
  abs-tmp-path: D:\tmp\tan-urp
  web-img-path: \image\
  tmp-upload-path: D:\tmp\tan-urp\
  cdn-host:
  oss:
    type: local
    prefix:


spring:
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:D:\tmp\tan-urp\image\